name: sentiment_env
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.11
  - anyio=4.2.0
  - argon2-cffi=21.3.0
  - attrs=23.1.0
  - babel=2.11.0
  - beautifulsoup4=4.12.3
  - bleach=4.1.0
  - bottleneck=1.3.7
  - certifi=2024.8.30
  - cffi=1.17.1
  - click=8.1.7
  - cycler=0.11.0
  - fonttools=4.51.0
  - h11=0.14.0
  - httpcore=1.0.2
  - httpx=0.27.0
  - idna=3.7
  - ipykernel=6.28.0
  - ipython=8.27.0
  - jinja2=3.1.4
  - joblib=1.4.2
  - jsonschema=4.19.2
  - jupyterlab=4.2.5
  - kiwisolver=1.4.4
  - lcms2=2.12
  - libpng=1.6.39
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.9.2
  - matplotlib-inline=0.1.6
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - nltk=3.9.1
  - numpy=1.26.4
  - openjpeg=2.5.2
  - pandas=2.2.2
  - pillow=10.4.0
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - readline=8.2
  - regex=2024.9.11
  - requests=2.32.3
  - scikit-learn=1.5.1
  - scipy=1.13.1
  - seaborn=0.13.2
  - six=1.16.0
  - soupsieve=2.5
  - sqlite=3.45.3
  - terminado=0.17.1
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tqdm=4.66.5
  - typing-extensions=4.11.0
  - wcwidth=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.5
  - spacy  # spaCy NLP library
  - pytorch  # PyTorch for model training

  # Asegúrate de que pip está instalado correctamente antes de usarlo
  - pip

  # Instalar con pip las bibliotecas que no están en conda o necesitan versiones específicas
  - pip:
      - transformers==4.44.2
      - datasets  # Hugging Face datasets
      - streamlit  # Streamlit para desplegar el dashboard
